### ISSUE TITLE
missing default Logger configuration

### ISSUE THREAD

**Issue by mirkof** [scaldi/scaldi-play#31]
Hello, 

We updated to Play 2.5 with Scaldi. We are using default `play.api.Logger`.

But I've notices that there is no Logger configuration...
https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-custom-application-loader

Or maybe I'm wrong and this unrelated. :/

And this is the error that we got when we tried to run the app in production:

```
Exception in thread "main" java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/slf4j/impl/StaticLoggerBinder"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:80)
        at play.api.libs.logback.LogbackLoggerConfigurator.configure(LogbackLoggerConfigurator.scala:62)
        at scaldi.play.ScaldiApplicationBuilder$$anonfun$realInjector$1.apply(ScaldiApplicationBuilder.scala:63)
        at scaldi.play.ScaldiApplicationBuilder$$anonfun$realInjector$1.apply(ScaldiApplicationBuilder.scala:63)
        at scala.Option.foreach(Option.scala:257)
        at scaldi.play.ScaldiApplicationBuilder.realInjector(ScaldiApplicationBuilder.scala:62)
        at scaldi.play.ScaldiApplicationBuilder.build(ScaldiApplicationBuilder.scala:88)
        at scaldi.play.ScaldiApplicationLoader.load(ScaldiApplicationLoader.scala:19)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**Comment by mirkof** [comment]
This was the actual problem, not Scaldi. 
https://github.com/playframework/playframework/issues/5997

Sorry and keep up the good work! :)
