### ISSUE TITLE
play 2.6 update

### ISSUE THREAD

**Issue by dsarosi** [scaldi/scaldi-play#32]
Is there any plan to update scaldi-play to work with play 2.6?

**Comment by elmalto** [comment]
I forked it in case anyone's interested. Works with 2.6, but I am only using it in development currently

https://github.com/elmalto/scaldi-play

**Comment by nessus42** [comment]
I tried out both the fork and the pull request, but I get an error that controllers.Application can't get found when I do "sbt run" and try to navigate to localhost:9000.

I was able to upgrade to Play 2.5 with scaldi-play and have my web site work. Any idea what's wrong?

Here's a stack trace:

```
[info] play.api.Play - Application started (Dev)
[error] application - 

! @7559nale3 - Internal server error, for (GET) [/] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassNotFoundException: controllers.Application]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:255)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180)
	at play.api.http.DefaultHttpErrorHandler$.onServerError(HttpErrorHandler.scala:286)
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:52)
	at play.core.server.Server$class.getHandlerFor(Server.scala:82)
	at play.core.server.AkkaHttpServer.getHandlerFor(AkkaHttpServer.scala:41)
	at play.core.server.AkkaHttpServer.getHandler(AkkaHttpServer.scala:214)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:194)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
	at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
Caused by: java.lang.ClassNotFoundException: controllers.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.javaClass(JavaMirrors.scala:555)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToJava$1.apply(JavaMirrors.scala:1211)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToJava$1.apply(JavaMirrors.scala:1203)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toJava$1.apply(TwoWayCaches.scala:49)
	at scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)

```

**Comment by daniels-ob** [comment]
You need to include Guice.

Then make sure your controllers either extend AbstractController or InjectedController.

https://www.playframework.com/documentation/2.6.x/Migration26#scala-controller-changes

**Comment by nessus42** [comment]
Thanks for the help.

Alas, I'm already including Guice and all my controllers already extend AbstractController.

I already had this all working for Play 2.5 with Scaldi, and with every controller being a DI'ed class, rather than an object. Now I'm trying to upgrade to Play 2.6, but I'm getting the aforementioned error.

**Comment by daniels-ob** [comment]
It's hard to pinpoint without seeing your code.  It's also hard to identify whether this can be isolated as a scaldi-play issue.  Can you share your controllers.Application class?

**Comment by nessus42** [comment]
I figured it out. I wasn't injecting `ControllerComponents` correctly. This was introduced in Play 2.6 and wasn't in Play 2.5. Now I have it working.

Thanks!

**Comment by nessus42** [comment]
Hi. Is this pull request going to be accepted anytime soon? We are putting it into production very soon, but it would be nice if it were "official".

**Comment by OlegIlyenko** [comment]
Sorry for the delay! Just released the v0.5.16: https://github.com/scaldi/scaldi-play/releases/tag/v0.5.16 (will take ~1h for maven cental to propagate the artifact)

**Comment by nessus42** [comment]
Cool, thanks!!!

**Comment by martin-g** [comment]
> You need to include Guice.

Why Guice has to be in the classpath ? 
I thought Scaldi is an alternative of Guice.
It seems Play is not very friendly to 3rd party DI libraries ?!

**Comment by nlhkh** [comment]
@nessus42 How do you inject the `ControllerComponents` ?

**Comment by elmalto** [comment]
Looking at the tests you should do

```
class ApplicationController(implicit inj: Injector, cc: ControllerComponents) extends AbstractController(cc) with Injectable {
  // ... ///
}```

**Comment by nlhkh** [comment]
Duh... It works now!
Thanks @elmalto 👍
